name       : museeks
version    : 0.13.0
release    : 1
source     :
    - https://github.com/martpie/museeks/archive/refs/tags/0.13.0.tar.gz : 8cd21f2f720780bab02b496e00315743f10dda6cb9af8452be0c4e39bc337257
homepage   : https://museeks.io/
license    : MIT
component  : multimedia.audio
networking : yes
summary    : A simple and clean music player.
description: |
    Museeks aims to be a simple and easy to use music player with a clean UI.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gbm)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(xshmfence)
    - git
    - yarn
setup      : |
    patch -p1 < $pkgfiles/0001-remove-build-targets.patch
    yarn install --frozen-lockfile
build      : |
    yarn build
    yarn package:l
install    : |
    export museeksdir=/usr/share/museeks
    install -dm00755 $installdir/$museeksdir
    install -dm00755 $installdir/usr/bin
    cp -R ./build/linux-unpacked/* $installdir/$museeksdir

    # Link binaries
    ln -s $museeksdir/museeks $installdir/usr/bin/museeks

    # Install icon
    install -Dm00644 ./src/images/logos/museeks.png $installdir/usr/share/icons/hicolor/256x256/apps/museeks.png

    # Install .desktop file
    install -Dm00644 $pkgfiles/museeks.desktop $installdir/usr/share/applications/museeks.desktop